### ISSUE TITLE
SightlyException on AEM 6.4

### ISSUE THREAD

**Issue by benediktbast** [PerficientDigital/AEM-DataLayer#11]
[data_layer_aem64_slingexception.txt](https://github.com/PerficientDigital/AEM-DataLayer/files/2679194/data_layer_aem64_slingexception.txt)

Hi, I installed this package to an AEM 6.4 Installation with the we-reatail democontent project. I am encoutering two issues there:
- The datalayer only works fine on author and publisher when logged on as aem user. When not logged on to aem a SightlyException occurs. The full message is attached as file, but the interesting part should be: 

`Caused by: javax.el.ELException: Error reading 'config' on type com.perficient.aem.datalayer.core.models.AEMDataLayerManager
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:87) [org.apache.sling.scripting.jsp:2.2.7.B002]
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:54) [org.apache.sling.scripting.jsp:2.2.7.B002]
        at org.apache.el.parser.AstValue.getValue(AstValue.java:123) [org.apache.sling.scripting.jsp:2.2.7.B002]
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:186)
        at org.apache.sling.scripting.jsp.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:975) [org.apache.sling.scripting.jsp:2.2.7.B002]
        at org.apache.jsp.apps.aemdatalayer.components.includedatalayer.includedatalayer_jsp._jspService(includedatalayer_jsp.java:178)
        at org.apache.sling.scripting.jsp.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [org.apache.sling.scripting.jsp:2.2.7.B002]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [org.apache.felix.http.servlet-api:1.1.2]
        at org.apache.sling.scripting.jsp.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:502) [org.apache.sling.scripting.jsp:2.2.7.B002]
        ... 221 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.perficient.aem.datalayer.core.models.AEMDataLayerManager.getConfig(AEMDataLayerManager.java:43) [com.perficient.aem.datalayer.core:0.2.3.SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:83) [org.apache.sling.scripting.jsp:2.2.7.B002]
        ... 229 common frames omitted`

 -  When logged on the datalayer works, but only product detail pages like /content/we-retail/us/en/products/equipment/surfing/the-stretch-longboard.html have a well populated datalayer, all other page types lack information.
`<script>
 window.digitalData = {
 "version ": "1.0",
 "page": {
 "pageInfo": {}
 },
 "event": []
 }
 </script>`

Can this be fixed for AEM 6.4 ?

**Comment by benediktbast** [comment]
Hi Gyus, meanwhile I found a workaround. I can give the anonymous user read permission to the path **/etc/cloudservices/aemdatalayer/MyDataLayerConfig**
Is this the recommended way, or can you fix something from your side?

**Comment by bsaravanaprakash** [comment]
Hi @benediktbast , just to let you know. This was a very useful infrastructure for implementing datalayer. I customized to use [sling config](https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration.html) avoiding /etc/ dependency. You may give a try.

**Comment by klcodanr** [comment]
Sorry for the slow turn on this one. I just pushed an update @benediktbast to fix the two issues you pointed out. Can you build it and double check on your end?

**Comment by klcodanr** [comment]
Fixed in: 8375f6051660cfc94a64506dff79bc864a15f4a5 and 3f226d981a2159c5afc557badfae2991bf6f3c68
