### ISSUE TITLE
Unnecessarily Escalated Logging

### ISSUE THREAD

**Issue by klcodanr** [PerficientDigital/AEM-DataLayer#12]
What it’s still disturbing me are a bunch of warnings regarding “no Digital Data config found” and (new) “ModelClass exceptions”. Here’s some of them:
 
23.01.2019 10:14:57.491 *WARN* [0:0:0:0:0:0:0:1 [1548234897489] GET /libs/cq/core/content/tools/cloudservices.html HTTP/1.1] com.perficient.aem.datalayer.core.models.AEMDataLayerConfig No Digital Data config found for /libs/cq/core/content/tools/cloudservices
23.01.2019 10:15:04.723 *WARN* [0:0:0:0:0:0:0:1 [1548234904721] GET /etc/cloudservices/aemdatalayer/myDataLayer.html HTTP/1.1] com.perficient.aem.datalayer.core.models.AEMDataLayerConfig No Digital Data config found for /etc/cloudservices/aemdatalayer/myDataLayer
23.01.2019 10:15:04.791 *INFO* [0:0:0:0:0:0:0:1 [1548234904790] GET /etc.clientlibs/settings/wcm/designs/default/resources.css HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.ClientLibraryProxyServlet Unable to proxy settings/wcm/designs/default/resources.css. No such library for settings/wcm/designs/default/resources
23.01.2019 10:15:28.374 *WARN* [0:0:0:0:0:0:0:1 [1548234928373] GET /etc/cloudservices/aemdatalayer/myDataLayer.html HTTP/1.1] com.perficient.aem.datalayer.core.models.AEMDataLayerConfig No Digital Data config found for /etc/cloudservices/aemdatalayer/myDataLayer
23.01.2019 10:15:28.520 *INFO* [0:0:0:0:0:0:0:1 [1548234928519] GET /etc.clientlibs/settings/wcm/designs/default/resources.css HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.ClientLibraryProxyServlet Unable to proxy settings/wcm/designs/default/resources.css. No such library for settings/wcm/designs/default/resources
23.01.2019 10:16:21.178 *WARN* [0:0:0:0:0:0:0:1 [1548234981174] GET /etc/cloudservices/aemdatalayer/myDataLayer/_jcr_content.datalayer.json/content/we-retail/it/it HTTP/1.1] com.perficient.aem.datalayer.core.models.AEMDataLayerConfig No Digital Data config found for /etc/cloudservices/aemdatalayer/myDataLayer
23.01.2019 10:16:21.185 *WARN* [0:0:0:0:0:0:0:1 [1548234981174] GET /etc/cloudservices/aemdatalayer/myDataLayer/_jcr_content.datalayer.json/content/we-retail/it/it HTTP/1.1] org.apache.sling.engine.impl.request.RequestData SlingRequestProgressTracker not found in request attributes
23.01.2019 10:16:21.194 *WARN* [0:0:0:0:0:0:0:1 [1548234981174] GET /etc/cloudservices/aemdatalayer/myDataLayer/_jcr_content.datalayer.json/content/we-retail/it/it HTTP/1.1] com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter Exception adapting request com.day.cq.wcm.core.impl.WCMComponentFilter$ForwardRequestWrapper@28ce4518 to ComponentDataElement:
 
 
23.01.2019 10:16:21.656 *WARN* [0:0:0:0:0:0:0:1 [1548234981174] GET /etc/cloudservices/aemdatalayer/myDataLayer/_jcr_content.datalayer.json/content/we-retail/it/it HTTP/1.1] com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter Exception adapting resource SyntheticResource, type=granite/contexthub/components/contexthub, path=/content/we-retail/it/it/jcr:content/contexthub to ComponentDataElement:
org.apache.sling.models.factory.ModelClassException: Could find model registered for resource type: granite/contexthub/components/contexthub
                at org.apache.sling.models.impl.ModelAdapterFactory.getModelFromResource(ModelAdapterFactory.java:1241) [org.apache.sling.models.impl:1.4.7.T20180205124646-b0647a3]
                at com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter.updateDataLayer(AEMDataLayerInterceptorFilter.java:148) [com.perficient.aem.datalayer.core:0.2.3.SNAPSHOT]
                at com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter.doFilter(AEMDataLayerInterceptorFilter.java:81) [com.perficient.aem.datalayer.core:0.2.3.SNAPSHOT]
 
23.01.2019 10:16:25.369 *WARN* [0:0:0:0:0:0:0:1 [1548234981174] GET /etc/cloudservices/aemdatalayer/myDataLayer/_jcr_content.datalayer.json/content/we-retail/it/it HTTP/1.1] com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter Exception adapting resource SyntheticResource, type=cq/cloudconfig/components/scripttags/footer, path=/content/we-retail/it/it/jcr:content/cloudconfig-footer to ComponentDataElement:
org.apache.sling.models.factory.ModelClassException: Could find model registered for resource type: cq/cloudconfig/components/scripttags/footer
                at org.apache.sling.models.impl.ModelAdapterFactory.getModelFromResource(ModelAdapterFactory.java:1241) [org.apache.sling.models.impl:1.4.7.T20180205124646-b0647a3]
                at com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter.updateDataLayer(AEMDataLayerInterceptorFilter.java:148) [com.perficient.aem.datalayer.core:0.2.3.SNAPSHOT]
                at com.perficient.aem.datalayer.core.filters.AEMDataLayerInterceptorFilter.doFilter(AEMDataLayerInterceptorFilter.java:81) [com.perficient.aem.datalayer.core:0.2.3.SNAPSHOT]
                at

**Comment by klcodanr** [comment]
Fixed in 0adbe9ef725cbc673fce4b13133eb08f01dd6c0a
